# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dask_airflow'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dask_airflow'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  dask_airflow:
    # This section configures the model settings for the entire project
    +materialized: view  # Default materialization for all models in this project

    # Specific model configuration for weather_model.sql
    weather_model:        # This matches the filename weather_model.sql
      +materialized: table  # If you want this model to be a table instead of a view
      # You can add other configurations specific to this model, e.g.:
      # +schema: staging  # Specify a schema if needed
      +tags: ['weather', 'api']  # Tags for categorizing models
