fuckin_dbt:
  outputs:
    dev:
      dbname: postgres
      host: airflow-docker-analytics-db-1
      pass: postgres
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres_user
  target: dev
